### PR TITLE
fix: swap lodash to only necessary packages

### PR DESCRIPTION
**Pull request by hvolschenk**
Not super necessary, but it is nice and concise.

### CODE REVIEW

**Comment by hvolschenk** [comment]
Awesome stuff! 👍

**Comment by tomchentw** [comment]
Could we do `lodash` directly with `babel-plugin-lodash` that cherry-pick the modules? That'll let us just depend on one `lodash` instead of many other deps. I can help a PR.
https://github.com/lodash/babel-plugin-lodash

**Comment by maicki** [comment]
@tomchentw If you wanna great a PR please go ahead. We currently don't have babel as dependency so I'm not sure if the `babel-plugin-lodash` would outweigh the cost of adding babel.

**Comment by tomchentw** [comment]
@maicki thank you. I've created #16

**Pull request merged**
