### PR TITLE
Direct users to a maintained fork

### PR DESCRIPTION
**Pull request by dawsbot**

### CODE REVIEW

**Comment by jonluca** [comment]
+1 on this

**Comment by maicki** [comment]
You mind just adding it to this PR, I don't think we need a different PR? Thanks!

**Comment by vzaidman** [comment]
Hey!
Thanks for the merge!

Maybe it's also a good time to deprecate the github and npm project.

Otherwise you will be spammed by issues and security issues from the different security providers

**Comment by vzaidman** [comment]
Yea I'm just about to release a new version with very nice typescript, custom hooks tracking and many more features

**Pull request merged**
