### PR TITLE
Support for React Hooks

### PR DESCRIPTION
**Pull request by adkenyon**
Resolves issues from #52

### CODE REVIEW

**Comment by adkenyon** [comment]
@dawsbot thanks for the stack trace! It might be a few weeks until I can look at this in depth, I will be vacationing and conferencing for a while.

**Comment by adkenyon** [comment]
@dawsbot I haven't been able to reproduce the issue with our React or React Native apps. Looking at the stacktrace I _think_ the issue is that your app has a class component with a read-only display name. I've put a guard to prevent the issue. Can you give it another try?

**Comment by adkenyon** [comment]
Also, I suspect that this issue may have existed prior to this PR

**Comment by siemiatj** [comment]
@maicki any news ? This is becoming a serious problem since the refs adoption is growing.

**Comment by adkenyon** [comment]
[React-Devtools](https://www.npmjs.com/package/react-devtools) should also help with identifying rerenders

**Pull request merged**
